version: '3'
services:
  postgis:
    image: kartoza/postgis
    ports:
    - "55432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASS: docker
      POSTGRES_DBNAME: qgisfeed

  qgisfeed:
    # Note you cannot scale if you use container_name
    container_name: qgisfeed
    build:
      context: .
      dockerfile: Dockerfile.testing
    command: /code/entrypoint_testing.sh
    ports:
    - "8000:8000"
    depends_on:
      - postgis
