version: "3.7"

services:

  postgis:
    image: kartoza/postgis:16-3.4
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ${QGISFEED_DOCKER_DBUSER}
      POSTGRES_PASS: ${QGISFEED_DOCKER_DBPASSWORD}
      POSTGRES_DBNAME: ${QGISFEED_DOCKER_DBNAME}
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: always
    healthcheck:
      test: "POSTGRES_PASS=$${QGISFEED_DOCKER_DBPASSWORD} pg_isready -h 127.0.0.1 -U ${QGISFEED_DOCKER_DBUSER} -d ${QGISFEED_DOCKER_DBNAME}"
    volumes:
      - ${QGISFEED_DOCKER_SHARED_VOLUME}:/var/lib/postgresql
    networks:
      internal:

  metabase:
    image: metabase/metabase:v0.46.6.1
    hostname: metabase-secrets
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_HOST: postgis
      MB_DB_USER: ${QGISFEED_DOCKER_DBUSER}
      MB_DB_PASS: ${QGISFEED_DOCKER_DBPASSWORD}
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: always
    networks:
      internal:

  qgisfeed:
    # Note you cannot scale if you use container_name
    container_name: qgisfeed
    image: xpirix/qgisfeed:production-1.4
    build:
      context: .
      dockerfile: Dockerfile.production
    environment:
      - QGISFEED_DOCKER_DBNAME
      - QGISFEED_DOCKER_DBUSER
      - QGISFEED_DOCKER_DBPASSWORD
    command: /code/entrypoint_production.sh
    expose:
      - "8000"
    volumes:
      - ${QGISFEED_DOCKER_SHARED_VOLUME}:/shared-volume
      - ../qgis-feed:/code
    depends_on:
      - postgis
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: always
    networks:
      internal:

  nginx:
    image: nginx:latest
    ports:
      - "80:8000"
      - "443:443"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    volumes:
      - ${QGISFEED_DOCKER_SHARED_VOLUME}:/shared-volume
      - ./config/nginx:/etc/nginx/conf.d
      - ./webroot:/var/www/webroot
      - ./certbot-etc:/etc/letsencrypt
      - ./certbot-var:/var/lib/letsencrypt
      - ./dhparam:/etc/ssl/certs
    restart: always
    networks:
      internal:

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./webroot:/var/www/webroot
      - ./certbot-etc:/etc/letsencrypt
      - ./certbot-var:/var/lib/letsencrypt
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/webroot --email admin@qgis.org --agree-tos --no-eff-email --force-renewal -d feed.qgis.org
  
  dbbackups:
    image: kartoza/pg-backup:16-3.4
    environment:
      DUMPPREFIX: PG_QGIS_FEED
      POSTGRES_DATABASE: ${QGISFEED_DOCKER_DBNAME}
      POSTGRES_HOST: postgis
      POSTGRES_PASS: ${QGISFEED_DOCKER_DBPASSWORD}
      POSTGRES_PORT: '5432'
      POSTGRES_USER: ${QGISFEED_DOCKER_DBUSER}
    volumes:
    - /mnt/backups/:/backups
    restart: on-failure
    depends_on:
      postgis:
        condition: service_healthy
    networks:
      internal:

networks:
    internal:

