version: '3.7'
services:
  postgis:
    image: kartoza/postgis:14-3.1
    platform: linux/amd64
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASS: docker
      POSTGRES_DBNAME: qgisfeed

  qgisfeed:
    build:
      context: .
      dockerfile: ./Dockerfile
    platform: linux/amd64
    command: /code/entrypoint_testing.sh
    environment:
      DJANGO_SETTINGS_MODULE: qgisfeedproject.settings_dev
    ports:
    - "8000:8000"
    links:
      - postgis
    depends_on:
      - postgis
    volumes:
      - ../qgis-feed:/code

  webpack:
    build:
      context: .
      dockerfile: ./Dockerfile
    platform: linux/amd64 
    command: npm start
    working_dir: /code
    volumes:
      - .:/code