version: '3.7'
services:
  postgis:
    image: kartoza/postgis:16-3.4
    platform: linux/amd64
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASS: docker
      POSTGRES_DBNAME: qgisfeed    
    volumes:
      - ${QGISFEED_DOCKER_SHARED_VOLUME}:/var/lib/postgresql
      - ${QGISFEED_BACKUP_VOLUME}:/backups
    # ports:
    # - "5436:5432"

  qgisfeed:
    # Note you cannot scale if you use container_name
    container_name: qgisfeed
    build:
      context: .
      dockerfile: ./Dockerfile
    platform: linux/amd64
    command: /code/entrypoint_testing.sh
    environment:
      DJANGO_SETTINGS_MODULE: qgisfeedproject.settings_dev
      QGISFEED_DOCKER_DBNAME: ${QGISFEED_DOCKER_DBNAME}
      QGISFEED_DOCKER_DBUSER: ${QGISFEED_DOCKER_DBUSER}
      QGISFEED_DOCKER_DBPASSWORD: ${QGISFEED_DOCKER_DBPASSWORD}
      QGIS_FEED_PROD_URL: ${QGIS_FEED_PROD_URL}
      QGISFEED_FROM_EMAIL: ${QGISFEED_FROM_EMAIL:-automation}
      EMAIL_BACKEND: ${EMAIL_BACKEND}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USE_TLS: ${EMAIL_USE_TLS}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER:-automation}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      SENTRY_DSN: ${SENTRY_DSN}
      SENTRY_RATE: ${SENTRY_RATE}
    ports:
    - "8000:8000"
    links:
      - postgis
    depends_on:
      - postgis
    volumes:
      - ../qgis-feed:/code
      - /Users/xpirix/Work/Dev/01-Kartoza/00-Data/feed.qgis.org/media:/code/qgisfeedproject/media
      - ./REQUIREMENTS.txt:/REQUIREMENTS.txt

  webpack:
    build:
      context: .
      dockerfile: ./Dockerfile
    platform: linux/amd64 
    command: npm start
    working_dir: /code
    volumes:
      - .:/code