# Generated by Django 4.2.24 on 2026-01-20 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_existing_entries(apps, schema_editor):
    """Set initial status for existing entries based on published flag"""
    QgisFeedEntry = apps.get_model("qgisfeed", "QgisFeedEntry")

    # Set published entries to 'published' status
    QgisFeedEntry.objects.filter(published=True).update(status="published")

    # Set unpublished entries to 'draft' status
    QgisFeedEntry.objects.filter(published=False).update(status="draft")


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("qgisfeed", "0014_alter_dailyqgisuservisit_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="qgisfeedentry",
            name="assigned_reviewer",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary reviewer assigned to this entry",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewing_entries",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned Reviewer",
            ),
        ),
        migrations.AddField(
            model_name="qgisfeedentry",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_review", "Pending Review"),
                    ("changes_requested", "Changes Requested"),
                    ("approved", "Approved"),
                    ("published", "Published"),
                ],
                db_index=True,
                default="draft",
                help_text="Current workflow status of the entry",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="qgisfeedentry",
            name="author",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authored_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="qgisfeedentry",
            name="publish_from",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Publication start (UTC)",
            ),
        ),
        migrations.AlterField(
            model_name="qgisfeedentry",
            name="publish_to",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="The entry will be hidden to users after this date. You can set this in the past to temove the entry from the users listing.",
                null=True,
                verbose_name="Publication end (UTC)",
            ),
        ),
        migrations.CreateModel(
            name="FeedEntryRevision",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("content", models.TextField(verbose_name="Content")),
                ("url", models.URLField(blank=True, null=True, verbose_name="URL")),
                (
                    "changed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Changed at"),
                ),
                (
                    "change_summary",
                    models.CharField(
                        blank=True,
                        help_text="Brief description of what changed",
                        max_length=255,
                        verbose_name="Change Summary",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="qgisfeed.qgisfeedentry",
                        verbose_name="Feed Entry",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feed Entry Revision",
                "verbose_name_plural": "Feed Entry Revisions",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="FeedEntryReview",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        help_text="Review feedback or comments", verbose_name="Comment"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("approve", "Approve"),
                            ("request_changes", "Request Changes"),
                            ("comment", "Comment"),
                        ],
                        help_text="Review action taken",
                        max_length=20,
                        verbose_name="Action",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="qgisfeed.qgisfeedentry",
                        verbose_name="Feed Entry",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feed Entry Review",
                "verbose_name_plural": "Feed Entry Reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RunPython(migrate_existing_entries, migrations.RunPython.noop),
    ]
