# Generated by Django 4.2.24 on 2026-01-21 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "qgisfeed",
            "0015_qgisfeedentry_assigned_reviewer_qgisfeedentry_status_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="qgisfeedentry",
            name="reviewers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Reviewers assigned to this entry",
                related_name="reviewing_entries",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned Reviewers",
            ),
        ),
        migrations.AlterField(
            model_name="qgisfeedentry",
            name="assigned_reviewer",
            field=models.ForeignKey(
                blank=True,
                help_text="Deprecated: Use reviewers field instead",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="legacy_reviewing_entries",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Legacy Assigned Reviewer",
            ),
        ),
    ]
