# Generated by Django 4.2.24 on 2026-03-03 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qgisfeed", "0017_feedentryrevision_field_changes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedentryreview",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Feed Entry Review",
                "verbose_name_plural": "Feed Entry Reviews",
            },
        ),
    ]
